const { jsPDF } = window.jspdf;
generate_pdf.addEventListener('click', (e) => {
	e.preventDefault();
	let x1 = 8;
	let x1_diff = 10;
	let x2 = 200;
	let x2_diff = 10;
	let x3 = 10;
	let x3_diff = 10;
	let y1 = 4;
	let y1_diff = 10;
	let y2 = 4;
	let y2_diff = 10;
	let y3 = 10;
	let y3_diff = 10;
	const doc = new jsPDF();
	console.log(doc);
	doc.addFont('RobotoMono-Regular.ttf', 'RobotoMono', 'normal');
	doc.setFont('RobotoMono', 'normal');
	doc.line(x1, y1, x2, y2);
	doc.text(`Klient: ${document.getElementById('client-name').value}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Klient posiada instalację?: ${document.getElementById('have_pv_installation').value}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Poziom biura: ${document.getElementById('office_level').options[document.getElementById('office_level').selectedIndex].text}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Numer umowy: ${document.getElementById('generated_id').value}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Moc instalacji: ${document.getElementById('calculated-power').value} kWp`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Moduł: ${document.getElementById('panel_type').options[document.getElementById('panel_type').selectedIndex].text}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Falownik: ${document.getElementById('inverter_type').options[document.getElementById('inverter_type').selectedIndex].text}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Ilość faz: ${document.getElementById('inverter_phase').value}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Miejsce instalacji: ${document.getElementById('place_of_installation').options[document.getElementById('place_of_installation').selectedIndex].text}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`System montazowy: ${document.getElementById('roofing').options[document.getElementById('roofing').selectedIndex].text}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Podnośnik: ${document.getElementById('lift').value == 0 ? 'Nie' : 'Tak'}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Większy falownik: ${document.getElementById('large_inverter').value == 0 ? 'Nie' : 'Tak'}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Ilość paneli: ${document.getElementById('number_of_panels').value} szt.`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Dodatkowe koszty: ${document.getElementById('additional_costs').value} zł`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`VAT: ${document.getElementById('vat_value').value == 0.08 ? '8%' : '23%'}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Odroczenie raty 2 msc: ${document.getElementById('deferment').value}`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Długość przewodu: ${document.getElementById('cable_length').value === '' ? '0' : document.getElementById('cable_length').value} metrów`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Długość przekopu: ${document.getElementById('trench_length').value === '' ? '0' : document.getElementById('trench_length').value} metrów`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Cena netto: ${Intl.NumberFormat('pl-PL').format(parseFloat(document.getElementById('suggest-price-netto').value).toFixed(2))} zł`, x3, y3);
	y1 += y1_diff;
	y2 += y2_diff;
	y3 += y3_diff;
	doc.line(x1, y1, x2, y2);
	doc.text(`Cena brutto: ${Intl.NumberFormat('pl-PL').format(parseFloat(document.getElementById('suggest-price').value).toFixed(2))} zł`, x3, y3);
	doc.setFontSize(10);
	doc.text(`Dokument wygenerowano dnia ${new Date().toLocaleDateString('PL-pl')} ${getSerializedTime('hours')}:${getSerializedTime('minutes')}. Wersja kalkulatora: ${document.getElementById('version').textContent}`, 10, doc.canvas.height - 10);

	doc.save(`${document.getElementById('client-name').value} ${document.getElementById('generated_id').value}.pdf`);
	doc.deletePage(0);
});

function getSerializedTime(unit) {
	const sanitazedUnit = unit.toLowerCase();
	switch (sanitazedUnit) {
		case 'hours':
			const hour = new Date().getHours().toLocaleString();
			return hour < 10 ? `0${hour}` : hour;
		case 'minutes':
			const minute = new Date().getMinutes().toLocaleString();
			return minute < 10 ? `0${minute}` : minute;
		case 'seconds':
			const second = new Date().getSeconds().toLocaleString();
			return second < 10 ? `0${second}` : second;
	}
}
